# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /s/bach/k/under/jenpyle/CS253/HW8

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /s/bach/k/under/jenpyle/CS253/HW8

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /s/bach/k/under/jenpyle/CS253/HW8/CMakeFiles /s/bach/k/under/jenpyle/CS253/HW8/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /s/bach/k/under/jenpyle/CS253/HW8/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hw8.tar

# Build rule for target.
hw8.tar: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hw8.tar
.PHONY : hw8.tar

# fast build rule for target.
hw8.tar/fast:
	$(MAKE) -f CMakeFiles/hw8.tar.dir/build.make CMakeFiles/hw8.tar.dir/build
.PHONY : hw8.tar/fast

#=============================================================================
# Target rules for targets named hw8

# Build rule for target.
hw8: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hw8
.PHONY : hw8

# fast build rule for target.
hw8/fast:
	$(MAKE) -f CMakeFiles/hw8.dir/build.make CMakeFiles/hw8.dir/build
.PHONY : hw8/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

Enemy.o: Enemy.cc.o

.PHONY : Enemy.o

# target to build an object file
Enemy.cc.o:
	$(MAKE) -f CMakeFiles/hw8.dir/build.make CMakeFiles/hw8.dir/Enemy.cc.o
.PHONY : Enemy.cc.o

Enemy.i: Enemy.cc.i

.PHONY : Enemy.i

# target to preprocess a source file
Enemy.cc.i:
	$(MAKE) -f CMakeFiles/hw8.dir/build.make CMakeFiles/hw8.dir/Enemy.cc.i
.PHONY : Enemy.cc.i

Enemy.s: Enemy.cc.s

.PHONY : Enemy.s

# target to generate assembly for a file
Enemy.cc.s:
	$(MAKE) -f CMakeFiles/hw8.dir/build.make CMakeFiles/hw8.dir/Enemy.cc.s
.PHONY : Enemy.cc.s

Gallery.o: Gallery.cc.o

.PHONY : Gallery.o

# target to build an object file
Gallery.cc.o:
	$(MAKE) -f CMakeFiles/hw8.dir/build.make CMakeFiles/hw8.dir/Gallery.cc.o
.PHONY : Gallery.cc.o

Gallery.i: Gallery.cc.i

.PHONY : Gallery.i

# target to preprocess a source file
Gallery.cc.i:
	$(MAKE) -f CMakeFiles/hw8.dir/build.make CMakeFiles/hw8.dir/Gallery.cc.i
.PHONY : Gallery.cc.i

Gallery.s: Gallery.cc.s

.PHONY : Gallery.s

# target to generate assembly for a file
Gallery.cc.s:
	$(MAKE) -f CMakeFiles/hw8.dir/build.make CMakeFiles/hw8.dir/Gallery.cc.s
.PHONY : Gallery.cc.s

test.o: test.cc.o

.PHONY : test.o

# target to build an object file
test.cc.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test.cc.o
.PHONY : test.cc.o

test.i: test.cc.i

.PHONY : test.i

# target to preprocess a source file
test.cc.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test.cc.i
.PHONY : test.cc.i

test.s: test.cc.s

.PHONY : test.s

# target to generate assembly for a file
test.cc.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test.cc.s
.PHONY : test.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... hw8.tar"
	@echo "... hw8"
	@echo "... test"
	@echo "... Enemy.o"
	@echo "... Enemy.i"
	@echo "... Enemy.s"
	@echo "... Gallery.o"
	@echo "... Gallery.i"
	@echo "... Gallery.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

